import NavBarre from "@/components/NavBarre/NavBarre";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <header>
        <NavBarre />
      </header>
      <body>{children}</body>
    </html>
  );
}
